"""Pydantic schemas for request and response validation."""

from typing import List, Optional
from pydantic import BaseModel, Field, field_validator


class QuestionRequest(BaseModel):
    """Schema for incoming user questions."""

    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The natural language question to ask the documents.",
        examples=["What are the main concepts discussed in the uploaded documents?"],
    )

    @field_validator("question")
    @classmethod
    def validate_non_empty(cls, value: str) -> str:
        trimmed = value.strip()
        if not trimmed:
            raise ValueError("Question cannot be empty or whitespace only.")
        return trimmed


class Source(BaseModel):
    """Schema representing the source location of retrieved context."""

    document: str = Field(..., description="Filename of the source document.")
    chunk_id: str = Field(..., description="Identifier of the specific chunk.")
    page: int = Field(..., description="Page number where the chunk originates.")


class QuestionResponse(BaseModel):
    """Schema for question answering response."""

    question: str = Field(..., description="The user's original question.")
    answer: str = Field(..., description="Grounded answer generated by Gemini.")
    sources: List[Source] = Field(
        default_factory=list,
        description="List of document citations and chunks supporting the answer.",
    )


class UploadResponse(BaseModel):
    """Schema for document upload response."""

    status: str = Field(..., description="Status of the upload operation.")
    documents_processed: int = Field(
        ..., description="Number of documents successfully processed."
    )
    chunks_created: int = Field(
        ..., description="Total number of chunks generated and indexed."
    )
    message: str = Field(..., description="Summary message.")


class HealthResponse(BaseModel):
    """Schema for API health status."""

    status: str = Field(..., description="Overall service status.")
    vector_store: str = Field(
        ..., description="Status of the FAISS vector store ('ready', 'empty')."
    )
    neo4j: str = Field(
        ..., description="Status of Neo4j connection ('connected', 'unavailable')."
    )
    gemini: str = Field(
        ..., description="Status of Gemini configuration ('configured', 'unavailable')."
    )


class DocumentItem(BaseModel):
    """Schema for a single document summary."""

    document_id: str = Field(..., description="Unique ID of the document.")
    document_name: str = Field(..., description="Original filename.")
    chunk_count: int = Field(..., description="Number of chunks stored for this document.")


class GraphStatusResponse(BaseModel):
    """Schema for Neo4j knowledge graph status."""

    status: str = Field(..., description="Connection or availability status.")
    entity_count: Optional[int] = Field(
        None, description="Total number of Entity nodes."
    )
    document_count: Optional[int] = Field(
        None, description="Total number of Document nodes."
    )
    chunk_count: Optional[int] = Field(
        None, description="Total number of Chunk nodes."
    )
    message: Optional[str] = Field(
        None, description="Additional status or error details."
    )


class EntityDetailsResponse(BaseModel):
    """Schema for querying details of a specific entity in the graph."""

    entity: str = Field(..., description="Entity name.")
    related_entities: List[str] = Field(
        default_factory=list, description="List of directly connected entities."
    )
    message: Optional[str] = Field(None, description="Optional status message.")


class RootResponse(BaseModel):
    """Schema for the API root endpoint."""

    message: str
    version: str
    status: str
